
  error_signup_email: '请填写邮箱'
  error_signup_email_exist: '该邮箱已经注册，请更换邮箱注册'
  error_signup_email_wrong: '请填写正确的邮箱格式'
  error_signup_password: '请填写密码' 
  error_signup_password_wrong: '两次密码填写不一致'
  error_signup_password_length: '密码长度为6-20'
  error_signup_password_format: '密码需要由英文字母和数字组成'
  error_signup_kids_count: '请选择您的育儿状况'
  error_signup_kids: '请选择你的孩子的性别和生日'
  error_signup_have_baby_time: '您填写的孕产期不正确'
  
  
  error_login_input: '请输入邮箱和密码'
  error_login_user_wrong: '邮箱或密码错误'
  error_login_no_email_check: '用户未进行邮件验证'
  error_locked_user: '此用户名已被封锁' 
  
  error_find_password_email: '您输入的邮箱未在本站注册'
  
  error_user_name: '请填写昵称'
  error_user_name_exist: '该昵称已经存在，请更换其他昵称'
  error_org_name_exist: '该机构名称已存在，请更换其他名称'
  error_user_name_format: '昵称不允许出现空格等非法字符'
  error_user_name_length: '昵称必须为1到10个字符'
  error_user_gender: '请填写性别' 
  error_user_birthyear: '请填写年代'
  error_user_birthday: '请填写生日'
  error_user_province: '请选择您所在的地区'
  error_user_city: '请选择您所在的城市'
  error_user_industry_id: '请选择你所在的行业'
  error_user_address: '请填写详细地址'
  error_user_post_code: '请填写邮政编码'
  
  error_order_owner_name: '请填写收件人姓名'
  error_order_owner_mobile: '请填写收件人手机'
  error_order_contact_name: '请填写联系人姓名'
  error_order_contact_mobile: '请填写联系人手机'
  error_order_contact_email: '请填写联系人Email'
  
  error_user_domain_format: '个性化域名不正确，请使用长度为4～20个字符的数字或者字母'
  error_user_domain_exist: '此个性域名已经被注册，请更换其他域名'
  
  error_user_password_old: '原密码输入错误'
  error_user_tag_ids: '请选择至少一个关注的话题'
 
  error_user_kid_name: '请填写宝贝昵称'
  error_user_kid_gender: '请填写宝贝性别'
  error_user_kid_birthday: '请填写宝贝生日'
  error_user_kid_education: '请填写宝贝教育情况'
  
  error_post_content_length: '请输入210个字以内的文字'
  error_post_score: '积分输入不正确'
  error_post_score_over: '没有足够的积分'
  
  error_event_user_join_num: '请填写参加人数'
  error_event_user_join_num_format: '参加人数必须为数字'
  error_event_user_email: '请填写您的Email'
  error_event_user_mobile: '请填写您的手机'
  error_event_user_signuped: '你已经报名了'
  
  error_message_on_user: '没有这个昵称的用户'
  error_message_on_fans_user: '只可以给粉丝发短信'
  error_message_user_name: '请输入用户昵称'
  error_message_content: '请输入300个字以内的文字'
  error_time_format: '输入的日期不正确'
  error_mobile_wrong: '请输入正确的手机号'
  
  error_presence_spot: '请填写地点名称'
  error_uniqueness_spot: '重复的地点名称'
  
  error_message_age_tags_csv_format_error: '上传的csv文本格式不正确，请检查后重新提交'
  rebuild_age_tags_success: '重新生成话题配置成功'
  
  best_answer: '这是最佳答案'
  best_answer_result: '此答案为最佳答案'
  
  time_label_second: '秒钟前'
  time_label_minute: '分钟前'
  time_label_half_min: '半分钟前'
  time_label_hour: '小时前'
  time_label_yes: '昨天'
  time_label_before: '前天'
  time_label_y: '年'
  time_label_m: '月'
  time_label_d: '日'
  birthyear: '后'
  today: '今天'
  age: '岁'
  day: '天'
  have_baby: '孕'
  no_kid_name: '还没有昵称'
  
  time_birthyears: '50|60|70|80|90'
  tiny_fonts: '宋体=宋体;黑体=黑体;仿宋=仿宋;楷体=楷体;隶书=隶书;幼圆=幼圆;'
  
  gender_label_m: '男'
  gender_label_w: '女'
  kid_m: '儿子'
  kid_w: '女儿'
  focus_him_m: '关注他'
  focus_him_w: '关注她'
  focus_him_: '关注机构'
  him_m: '他'
  him_w: '她'
  
  
  education_names: '亲子园|幼儿园|小学|初中|高中|本科|研究生|其他'
  no_age: '全部'
  ages_all: '不限年龄'
  tags_all: '不限话题'
  no_category: '自由晒'
  reward_tag: '有奖晒'
  forward_post: '转晒'
  no_kids: '没有孩子'
  no_book_page_text: '在这里写文字'
  
  success_favorite_post: '已收藏'
  success_follow_user: '已关注'
  success_cancel: '已取消'
  success_hide: '已隐藏'
  success_sms_invite: '已经发送飞信好友邀请到您的手机，回复“是”即可收到短信提醒'
  cancel_follow: '取消关注'
  cancel_fans: '移除粉丝'
  add_follow: '加关注'
  set_vip_user: '设为天使'
  cancel_vip_user: '取消天使'
  
  post_comment: '评论'
  post_answer: '回答'
  
  mamashai: '妈妈晒'
  email_mamashai: '【妈妈晒】'
  email_dear: '亲爱的'
  email_signup_title: '请确认您在妈妈晒的注册邮箱'
  email_password_title: '重置您的妈妈晒登录密码'
  email_invite_title_pre: '来自好友'
  email_invite_title_post: '的妈妈晒邀请' 
  email_notify_comment_pre: '你在妈妈晒收到'
  email_notify_comment_post: '的评论啦' 
  email_notify_gift_title: '你在妈妈晒收到礼物啦'
  email_notify_message_title: '你在妈妈晒收到私信啦'
  
  kid_star_1: '牡羊'
  kid_star_2: '金牛'
  kid_star_3: '双子'
  kid_star_4: '巨蟹'
  kid_star_5: '狮子'
  kid_star_6: '处女'
  kid_star_7: '天秤'
  kid_star_8: '天蝎'
  kid_star_9: '射手'
  kid_star_10: '魔羯'
  kid_star_11: '水瓶'
  kid_star_12: '双鱼'
  kid_star_postfix: '座'
  
  quik_look: '快来看看'
  de: '的'
  space: '空间'
  
  kid_gender_m: '男孩'
  kid_gender_w: '女孩'
  
  send_gift_to_users: '赠送礼物给：'
  
  
  score_signup: '注册新用户'
  score_create_question: '发表提问'
  score_delete_question: '删除提问'
  score_create_age_or_tag: '参与年龄段和话题'
  score_delete_age_or_tag: '删除话题晒品'
  score_create_reward_tag: '参与有奖晒'
  score_delete_reward_tag: '删除有奖晒晒品'
  score_create_mobile_post: '用短信发布晒品'
  score_delete_mobile_post: '删除手机发布的晒品'
  score_create_forward_post: '被转晒'
  score_delete_forward_post: '被撤销转晒'
  score_create_favorite_post: '被收藏'
  score_delete_favorite_post: '被撤销收藏'
  score_create_fans: '被关注'
  score_delete_fans: '被取消关注'
  score_over_50_follows: '首次超过100个关注'
  score_user_logo: '首次上传用户头像'
  score_user_kid_logo: '首次上传宝宝头像'
  score_user_domain: '首次填写个性域名'
  score_user_profile: '首次完成个人资料'
  score_user_kid_profile: '首次完成宝宝资料'
  score_user_blogs: '首次关联博客'
  score_user_mobile: '首次绑定手机'
  score_invite_user: '邀请好友成功注册'
  score_admin_delete_post: '违规发言被管理员删除'
  score_send_gift: '送礼物'
  score_reward_question: '悬赏提问'
  score_best_answer: '获得最佳答案悬赏'
  score_user_book_score: '订购宝贝图书'
  score_cancel_event_signup: '取消活动报名'
  score_create_spot_tag: '晒地点'
  score_delete_spot_tag: '删除啥地点'
  score_create_order: '购买商品'
  score_login_one_day: '登录'
  score_invite_user: '邀请好友'
  
  from_forward: '转自'
  from_post: '来自'
  from_sms: '手机短信'
  from_wap: '妈妈晒手机版'
  from_blog: '同步博客'
  from_139: '139说客'
  from_mm: '妈妈晒'
  
  user_book_title: '的宝贝图书'
  user_book_back_title: '在妈妈晒'
  user_book_author1: '编辑'
  user_book_author2: '排版'
  
  about_page_title_team: '妈妈晒团队'
  about_page_key_team: '妈妈晒团队'
  about_page_title_contact: '联系妈妈晒'
  about_page_key_contact: '联系妈妈晒，用户沟通，商务合作，公共关系，投资者关系。'
  about_page_title_joinus: '加入妈妈晒'
  about_page_key_joinus: '加入妈妈晒，招聘，招募。'
  about_page_title_aboutus: '关于妈妈晒'
  about_page_key_aboutus: '关于妈妈晒，介绍、愿景、团队。'
  about_page_title_index: '个性主页 网站导航'
  about_page_key_index: '个性主页 网站导航。'
  about_page_title_user_apply: '妈妈晒招募天使妈爸和隐形翅膀啦!'
  about_page_key_user_apply: '妈妈晒招募天使妈爸和隐形翅膀啦!'
  
  pub_page_title_long_posts: '育儿资讯 大晒台'
  pub_page_key_long_posts: '育儿资讯 大晒台'
  pub_page_title_index: '大晒台首页'
  pub_page_key_index: '大晒台首页'
  pub_page_title_posts: '随便看看 大晒台'
  pub_page_key_posts: '随便看看，大晒台。'
  pub_page_title_hot_posts: '热门晒品 大晒台'
  pub_page_key_hot_posts: '热门晒品，大晒台，转发最多，评论最多，收藏最多，热门地点，热门活动。'
  pub_page_title_hot_users: '超级晒主 大晒台'
  pub_page_key_hot_users: '超级晒主，大晒台，明星妈妈，名人妈妈，超级妈妈，专业妈妈，育儿机构。'
  pub_page_title_ranks: '排行榜 大晒台'
  pub_page_key_ranks: '排行榜，大晒台，人气排行，积分排行，评价排行。'
  pub_page_title_info_posts: '资讯 大晒台'
  pub_page_key_info_posts: '资讯，大晒台，消息，知识，常识，经验，观点，八卦。'
  pub_page_title_posts_ask: '问答 大晒台'
  pub_page_key_posts_ask: '问答，大晒台，育儿问答，养育问答，养育困惑，教育问答。'
  pub_page_title_posts_spot: '地点 大晒台'
  pub_page_key_posts_spot: '地点，大晒台，地图，出行，亲子游。'
  pub_page_title_posts_event: '活动 大晒台'
  pub_page_key_posts_event: '活动，大晒台。'
  pub_page_title_great_posts: '精彩话题  大晒台'
  pub_page_key_great_posts: '精彩话题，大晒台。'
  pub_page_title_age_great_posts: '精彩话题  大晒台'
  pub_page_key_age_great_posts: '精彩话题，大晒台。'
  pub_page_title_baby_books: '宝贝自传  大晒台'
  
  
  
  page_up: '上一页'
  page_down: '下一页'
  age_str: '岁'
  
  book_upload_pictures: '晒图片'
  
  user_skins: '默认|白天|夜晚|圣诞|沙滩|灰色格调|春天|光影|新春|蝴蝶|Hello Kity|星空'
  book_skins: '喜洋洋|虎年新春'
  book_page_layouts: '版式一|版式二|版式三|版式四|版式五|版式六|版式七|版式八|版式九|版式十'
  book_layouts: '图片左上|图片右下|图片居下|图片中左'
  
  sms_notify_gift: '您在妈妈晒收到了一个礼物，登录妈妈晒即可查看。'
  sms_notify_message: '您在妈妈晒收到了一封未读私信，登录妈妈晒即可查看。'
  
 
  book_post_tags: '宝贝语录|宝贝故事|宝贝成长|女人心情|亲子关系'
  
  week_days_cn: '星期一|星期二|星期三|星期四|星期五|星期六|星期日'
  
  100_score_notice: '：由于你在妈妈晒人气高，晒品受欢迎，你获得了5个用户邀请名额的奖励！邀请那些你熟悉的好妈妈、好爸爸一起来晒吧：）同时，请耐心辅导他们啊，如果你邀请的人：注册后上传了头像、完善了个人资料、发了晒品，那么你也将获得20个积分的奖励！晒一点，就发光！'
  
  event_pay_tps: '免费|AA自助|按人次收费'
  event_unit_tps: '一大人|一大人一孩子|一家三口'
  event_join_tps: '任何注册用户|我关注的人|我的粉丝'
  
  posts_rate_count_label: '人评价'
  my_follows: '我关注的人'
  user_tps: '心灵|教育|饮食|读书|医护|其他'
  org_tps: '教育|商家|医护|俱乐部|休闲|饮食|媒体|其他'
  
  post_rate_labels: '很差|较差|还行|推荐|力荐'

  info_users_id: [1141 , 1147 , 1146 , 1142 , 1143 , 1144 , 1153 , 1152 , 1151 , 1150 , 1149 , 1148]
  info_check_box: ' 发布为资讯'
  
  
  